import type { Config } from "tailwindcss";

/**
 * Every value below resolves to a CSS custom property defined in src/tokens/*.css.
 * Components must never use raw hex/px values — only these utility classes —
 * so the whole library re-themes by editing the token files alone.
 */
export default {
  content: ["./src/**/*.{ts,tsx}", "./.storybook/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-family-sans)"],
      },
      fontSize: {
        xs: "var(--primitives-font-size-xs)",
        sm: "var(--primitives-font-size-sm)",
        base: "var(--primitives-font-size-base)",
        lg: "var(--primitives-font-size-lg)",
        xl: "var(--primitives-font-size-xl)",
        "2xl": "var(--primitives-font-size-2xl)",
        "3xl": "var(--primitives-font-size-3xl)",
        "4xl": "var(--primitives-font-size-4xl)",
        "5xl": "var(--primitives-font-size-5xl)",
      },
      fontWeight: {
        regular: "var(--primitives-font-weight-regular)",
        medium: "var(--primitives-font-weight-medium)",
        semibold: "var(--primitives-font-weight-semibold)",
        bold: "var(--primitives-font-weight-bold)",
      },
      lineHeight: {
        none: "var(--primitives-line-height-none)",
        tight: "var(--primitives-line-height-tight)",
        snug: "var(--primitives-line-height-snug)",
        normal: "var(--primitives-line-height-normal)",
        relaxed: "var(--primitives-line-height-relaxed)",
      },
      spacing: {
        0: "var(--primitives-spacing-0)",
        px1: "var(--primitives-spacing-1)",
        px2: "var(--primitives-spacing-2)",
        px3: "var(--primitives-spacing-3)",
        px4: "var(--primitives-spacing-4)",
        px5: "var(--primitives-spacing-5)",
        px6: "var(--primitives-spacing-6)",
        px7: "var(--primitives-spacing-7)",
        px8: "var(--primitives-spacing-8)",
        px10: "var(--primitives-spacing-10)",
        px12: "var(--primitives-spacing-12)",
        px14: "var(--primitives-spacing-14)",
        px16: "var(--primitives-spacing-16)",
        px20: "var(--primitives-spacing-20)",
        px24: "var(--primitives-spacing-24)",
        px28: "var(--primitives-spacing-28)",
        px32: "var(--primitives-spacing-32)",
        px40: "var(--primitives-spacing-40)",
        px48: "var(--primitives-spacing-48)",
        px56: "var(--primitives-spacing-56)",
        px64: "var(--primitives-spacing-64)",
        "space-xs": "var(--semantic-space-xs)",
        "space-sm": "var(--semantic-space-sm)",
        "space-md": "var(--semantic-space-md)",
        "space-lg": "var(--semantic-space-lg)",
        "space-xl": "var(--semantic-space-xl)",
        "space-2xl": "var(--semantic-space-2xl)",
      },
      borderRadius: {
        none: "var(--primitives-radius-none)",
        xs: "var(--primitives-radius-xs)",
        sm: "var(--primitives-radius-sm)",
        md: "var(--primitives-radius-md)",
        lg: "var(--primitives-radius-lg)",
        xl: "var(--primitives-radius-xl)",
        "2xl": "var(--primitives-radius-2xl)",
        "3xl": "var(--primitives-radius-3xl)",
        full: "var(--primitives-radius-full)",
        "control-sm": "var(--semantic-radius-control-sm)",
        "control-md": "var(--semantic-radius-control-md)",
        "control-lg": "var(--semantic-radius-control-lg)",
        card: "var(--semantic-radius-card)",
        pill: "var(--semantic-radius-pill)",
      },
      borderWidth: {
        hairline: "var(--primitives-border-width-hairline)",
        thick: "var(--primitives-border-width-thick)",
      },
      colors: {
        bg: {
          canvas: "var(--semantic-bg-canvas)",
          surface: "var(--semantic-bg-surface)",
          "surface-secondary": "var(--semantic-bg-surface-secondary)",
          "surface-tertiary": "var(--semantic-bg-surface-tertiary)",
          inverse: "var(--semantic-bg-inverse)",
          brand: "var(--semantic-bg-brand)",
          "brand-hover": "var(--semantic-bg-brand-hover)",
          "brand-active": "var(--semantic-bg-brand-active)",
          "brand-subtle": "var(--semantic-bg-brand-subtle)",
          success: "var(--semantic-bg-success)",
          "success-subtle": "var(--semantic-bg-success-subtle)",
          warning: "var(--semantic-bg-warning)",
          "warning-subtle": "var(--semantic-bg-warning-subtle)",
          danger: "var(--semantic-bg-danger)",
          "danger-subtle": "var(--semantic-bg-danger-subtle)",
          info: "var(--semantic-bg-info)",
          "info-subtle": "var(--semantic-bg-info-subtle)",
          overlay: "var(--semantic-bg-overlay)",
        },
        text: {
          primary: "var(--semantic-text-primary)",
          secondary: "var(--semantic-text-secondary)",
          tertiary: "var(--semantic-text-tertiary)",
          disabled: "var(--semantic-text-disabled)",
          inverse: "var(--semantic-text-inverse)",
          brand: "var(--semantic-text-brand)",
          "on-brand": "var(--semantic-text-on-brand)",
          success: "var(--semantic-text-success)",
          warning: "var(--semantic-text-warning)",
          danger: "var(--semantic-text-danger)",
          info: "var(--semantic-text-info)",
          link: "var(--semantic-text-link)",
        },
        border: {
          DEFAULT: "var(--semantic-border-default)",
          subtle: "var(--semantic-border-subtle)",
          strong: "var(--semantic-border-strong)",
          brand: "var(--semantic-border-brand)",
          success: "var(--semantic-border-success)",
          warning: "var(--semantic-border-warning)",
          danger: "var(--semantic-border-danger)",
          focus: "var(--semantic-border-focus)",
        },
        icon: {
          primary: "var(--semantic-icon-primary)",
          secondary: "var(--semantic-icon-secondary)",
          brand: "var(--semantic-icon-brand)",
          "on-brand": "var(--semantic-icon-on-brand)",
          disabled: "var(--semantic-icon-disabled)",
        },
      },
    },
  },
  plugins: [],
} satisfies Config;
